# Generated by Django 3.0.3 on 2020-03-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200310_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='timestamp',
            new_name='Joined',
        ),
    ]
