# Generated by Django 3.0.3 on 2020-03-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200310_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Joined',
            new_name='joined',
        ),
    ]
