# Generated by Django 3.0.3 on 2020-03-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200310_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='joined',
            new_name='created_on',
        ),
    ]
